all: build run_task1 run_task2 run_task3 run_task4 run_task5 run_bonus clean

build:
	gcc -o exe main.c

run_task1:
	./exe 1

run_task2:
	./exe 2

run_task3:
	./exe 3

run_task4:
	./exe 4

run_task5:
	./exe 5

run_bonus:
	./exe 5

clean:
	rm -f exe
